version: '2'
services:
  peopleprofile-app:
    image: peopleprofile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://peopleprofile-mssql:1433;database=PeopleProfile
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8091:8091
  peopleprofile-mssql:
    extends:
      file: mssql.yml
      service: peopleprofile-mssql
